### PR TITLE
Adding union pagination

### PR DESCRIPTION
**Pull request by lwiyninger-mdsol**
# Feature

We needed a way to create a paginated table with scopes from different models, so I'm proposing a modification to this gem to return an array of items when multiple scopes are passed in. 

# Screenshots

N/A

# Tests

bundle exec rspec spec
```
Finished in 0.25282 seconds
25 examples, 0 failures
```

### CODE REVIEW

File: lib/pagem.rb [hunk 1]
```diff
@@ -6,38 +6,41 @@ class Pagem
...
-      style: "background-image:url(" + (options[:global_url] ? icon.to_s : "/images/medidata_buttons/#{icon}.gif") + ")",
+      style: "background-image:url(#{options[:global_url] ? icon.to_s : "/images/medidata_buttons/#{icon}.gif"})",
       global_url: nil
      )
     link_to text, url, options
   end
 
-  def scope
-    @scope
-  end
```
Comment (lwiyninger-mdsol) [inline lib/pagem.rb]: Moved to the built-in ```attr_reader``` method

**Comment by sllewelyn-mdsol** [comment]
Did you mean master?

File: lib/pagem.rb [hunk 2]
```diff
@@ -6,38 +6,41 @@ class Pagem
...
   # Returns a scope for the currently selected page, or an empty scope if current_page is not valid.
   def paged_scope
     (current_page > 0) ? scope.limit(items_per_page).offset((current_page - 1) * items_per_page) : scope.where('0=1')
   end
 
-  def items_per_page
-    @items_per_page
-  end
+  # Returns an array of hashes containing the requested records. Used when pulling records from multiple tables.
+  def paged_union_results
```
Comment (sllewelyn-mdsol) [inline lib/pagem.rb]: Is there some way we can do this without the pager gem having knowledge of the db?

**Comment by lwiyninger-mdsol** [comment]
Yes.

File: lib/pagem.rb (hunk 2 above)
Comment (lwiyninger-mdsol) [inline lib/pagem.rb]: What do you mean? As far as I can tell, everything's pretty generic.

File: Gemfile [hunk 3]
```diff
@@ -4,6 +4,7 @@ source "http://gems.github.com"
 
 gem "rails",                "=3.1.12"
 gem "echoe"
+gem "sqlite3"
```
Comment (cherbst-medidata) [inline Gemfile]: Why do we need sqlite here now?

File: lib/pagem.rb [hunk 4]
```diff
@@ -6,38 +6,41 @@ class Pagem
...
+    sql_statements = scope.map { |s| s.except(:select).select("#{s.primary_key} AS id, #{s.klass} AS type").to_sql }
+    pagination_clause = "LIMIT #{items_per_page} OFFSET #{(current_page - 1) * items_per_page}"
+    order_clause = @order ? " ORDER BY #{@order.map(&:to_s).join(', ')}" : ''
+    query = "#{sql_statements.join(' UNION ')}#{order_clause} #{pagination_clause}"
+    query_results = ActiveRecord::Base.connection.select_all(query)
 
-  def count
-    @count
+    query_results.map { |record_hash| record_hash['type'].constantize.find(record_hash['id']) }
```
Comment (cherbst-medidata) [inline lib/pagem.rb]: I don't think this will be performant, won't this do a single find for every returned record? What happens with 500k inventory items?

File: Gemfile (hunk 3 above)
Comment (lwiyninger-mdsol) [inline Gemfile]: I'm not entirely sure, but for some reason the specs were failing without it.

File: lib/pagem.rb (hunk 4 above)
Comment (lwiyninger-mdsol) [inline lib/pagem.rb]: The number of returned records will be limited to one page of results, so 10 by default. (I don't love this either, but it's the only way I could find to actually return the objects themselves instead of an array of hashes.)

Comment (cherbst-medidata) [inline lib/pagem.rb]: This will also lose the associations won't it, making a few N+1 queries for
every row?

**Comment by cherbst-medidata** [comment]
Could we try to use Kaminari instead? That looks like it will let us paginate a collection that is the result of 2 queries:

```
(byebug) p paginate_collection(Shipment.all + Study.all, :inventory_items_url)

[#<Shipment id: 1, tracking_number: nil, name: "10001", origin_site_id: nil, destination_site_id: 1, origin_depot_id: 1, destination_depot_id: nil, date_shipped: nil, date_received: nil, shipper_confirmation_code: nil, site_confirmation_code: nil, study_id: 101, status: 1, status_changed_at: "2010-01-01 12:59:59", quarantine_id: nil, uuid: "TEST-CASE-UUID-SHIPMENT", alert_last_sent: nil, date_requested: "2010-01-01 12:59:59", manual: false>, #<Study id: 101, study_design_id: 1, name: "Test Study", external_id: "101", parent_study_id: nil, environment_id: nil, live: false, external_name: nil, rand_only: false, unblinded: false, is_shipping_algorithm_running: false, randomization_api_locked: false, dispensation_api_locked: false, include_address_in_shipping_email: false, allow_quarantining: false, file_upload_rules: 0, needs_design_by_wizard: false, can_generate_blocks: true, advanced_dosing: true, capping: false, subject_identification_version: 0, new_countries_require_qp_release: false, lots_are_blinded: false, conditional_treatment_unblinded_subjects: 0>]
```

**Comment by lwiyninger-mdsol** [comment]
Where are you finding ```paginate_collection```? It doesn't appear anywhere in the Kaminari docs.

File: lib/pagem.rb (hunk 4 above)
Comment (lwiyninger-mdsol) [inline lib/pagem.rb]: I have no idea what you mean by this.

**Comment by cherbst-medidata** [comment]
You get paginate_collection when you include ApiPagination

```
class Api::V1::ShipmentsController < ActionController::Base
  include ApiPagination
```

File: lib/pagem.rb (hunk 4 above)
Comment (cherbst-medidata) [inline lib/pagem.rb]: OK we define all these associations:

```
    @inventory_items = @inventory_items.includes(:quarantine, :lot, depot: [:medidata_depot], site: [:medidata])
```

if you do a find like this without includes where does the lot name, AT name, etc come from? A new query right?

**Comment by lwiyninger-mdsol** [comment]
I'm not seeing it there, either. In any case, with the code snippet you've provided me, it looks like you have to gather the objects first before paginating? That's the exact opposite of what I'm trying to do here.

File: lib/pagem.rb (hunk 4 above)
Comment (lwiyninger-mdsol) [inline lib/pagem.rb]: Ah, I see. Again, I don't like it, but I also don't see any better ideas that don't cause us to load 500k objects in memory.

**Comment by cherbst-medidata** [comment]
You can test passing scopes or filtering before passing to paginate_collection. The proof of concept is getting 2 different objects out of it in the same array.

**Comment by lwiyninger-mdsol** [comment]
I tried calling paginate_collection with just a scope as the first argument, and it looks like it's loading the collection before paginating. Note the timestamps:

```
14:12:55 balance.1                        | (byebug) paginated_collection(@inventory_items, :inventory_items_url)
14:16:01 balance.1                        | *** NoMethodError Exception: undefined method `paginated_collection' for #<InventoryItemsController:0x007fe197afaa70>
```
I'm reasonably certain that the 3-minute delay comes from loading the objects and not the method error (to be honest, I'm still not entirely sure what that argument is supposed to be).

**Comment by mahmed-mdsol** [comment]
Closing this in favor of PagemMultiscope introduced in #4. Maybe we can adapt something like this later if needed.
